from __future__ import annotations

PROBABILITY_CROSSOVER = 0.75
PROBABILITY_MUTATION = 0.01
NUMBER_OF_GENERATIONS = 50
MAX_DEPTH = 15
POPULATION_SIZE = 50
SELECTION_METHOD = ("tournament", 2)
N_ELITES = 1
RESULTS_FOLDER = "results"
